<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Image optimizer</title>
    <link rel="stylesheet" href="css/main.css">
    <script type="application/javascript" src="js/main.js"></script>
</head>
<body>
    <div class="blk">
    	<h1 class="t-c">Files optimizer</h1>
    	<label for="inputFile" id="dragcont">Drag files here</label>
        <input type="file" id="inputFile" class="inpFile" multiple>
        <div id="log">
            
        </div>
    </div>
</body>
</html>
